Repository mailpoet/mailpoet, pull requests merged in 2024-08, with the labels that each got.

#5763 Add commands deleting and verifying release zip [MAILPOET-5678]
  mailpoet/RoboFile.php
Labels: twin

#5768 Update acceptance Create an account label
  mailpoet/tests/_support/AcceptanceTester.php
  mailpoet/tests/acceptance/Subscriptions/WooCheckoutBlocksCest.php
Labels: acceptance

#5780 Fix flaky acceptance segment test
  mailpoet/tests/_support/AcceptanceTester.php
  mailpoet/tests/acceptance/Segments/CreateSegmentEmailAbsoluteCountCest.php
Labels: acceptance

#5783 Update WordPress and plugins in CI jobs
  .circleci/config.yml
Labels: automated, check-versions

#5790 Fix dual buttons in Outlook [MAILPOET-6190]
  mailpoet/lib-3rd-party/pquery/gan_node_html.php
  mailpoet/lib/Newsletter/Renderer/Renderer.php
  mailpoet/tests/integration/Newsletter/RendererTest.php
  mailpoet/tests/integration/Statistics/GATrackingTest.php
Labels: priority in QA

#5791 Update WordPress and plugins in CI jobs
  .circleci/config.yml
Labels: automated, check-versions
