Repository mailpoet/mailpoet, pull requests merged in 2024-01, with the labels that each got.

#5365 Display different notices before Feb 1st [MAILPOET-5819]
  mailpoet/lib/Util/Notices/SenderDomainAuthenticationNotices.php
  mailpoet/tests/integration/Util/Notices/SenderDomainAuthenticationNoticesTest.php
  mailpoet/tests/integration/_bootstrap.php
Labels: priority in QA

#5396 Update k6 version and reduce nightly test cycle
  mailpoet/tests/performance/scenarios.js
  mailpoet/tools/k6.php
Labels: k6 performance

#5397 Increase limits for legacy emails [MAILPOET-5850]
  mailpoet/assets/js/src/automation/listing/store/legacy-actions.tsx
Labels: priority in QA

#5400 Ensure invalid tasks don't prevent new post notifications [MAILPOET-5853]
  mailpoet/lib/Newsletter/NewslettersRepository.php
  mailpoet/lib/Newsletter/Scheduler/PostNotificationScheduler.php
Labels: priority in QA

#5323 Refactor Mailer::formatSubscriberNameAndEmailAddress() to use Doctrine
  mailpoet/lib/Cron/Workers/SendingQueue/Tasks/Mailer.php
  mailpoet/lib/Mailer/Mailer.php
  mailpoet/tests/integration/Mailer/MailerTest.php
Labels: Do not release before 2024
